services:
  # Backend API Python
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: claude-api
    hostname: api
    restart: unless-stopped
    ports:
      - "8989:8989"
    env_file:
      - .env.docker
    environment:
      - HOST=0.0.0.0
      - PORT=8989
      - PYTHONPATH=/app:/app/claude-code-sdk-python
    volumes:
      # Persistência das sessões usando volumes nomeados
      - api_sessions:/app/sessions
      # Logs da aplicação
      - api_logs:/app/logs
      # Dados da aplicação
      - api_data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: []

  # Frontend Next.js
  frontend:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: claude-frontend
    hostname: frontend
    restart: unless-stopped
    ports:
      - "3040:3040"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
      - PORT=3040
      - HOSTNAME=0.0.0.0
      # URL interna para comunicação direta com a API
      - NEXT_PUBLIC_API_URL=http://api:8989
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3040/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - api


  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: claude-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./logs/redis:/var/log/redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  # Volumes para persistência de dados da API
  api_sessions:
    name: claude-api-sessions
    driver: local
  api_data:
    name: claude-api-data
    driver: local
  api_logs:
    name: claude-api-logs
    driver: local
  # Volume para Redis (opcional)
  redis-data:
    driver: local